# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_feed.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeFeedWindow(object):
    def setupUi(self, ChangeFeedWindow):
        ChangeFeedWindow.setObjectName("ChangeFeedWindow")
        ChangeFeedWindow.resize(800, 453)
        self.centralwidget = QtWidgets.QWidget(ChangeFeedWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #242424;\n"
"    font-family: Roboto;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: 100px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.selectApp = QtWidgets.QComboBox(self.centralwidget)
        self.selectApp.setMinimumSize(QtCore.QSize(500, 40))
        self.selectApp.setObjectName("selectApp")
        self.horizontalLayout.addWidget(self.selectApp)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.selectEmployee = QtWidgets.QComboBox(self.centralwidget)
        self.selectEmployee.setMinimumSize(QtCore.QSize(350, 40))
        self.selectEmployee.setObjectName("selectEmployee")
        self.horizontalLayout_2.addWidget(self.selectEmployee)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.selectFeed = QtWidgets.QComboBox(self.centralwidget)
        self.selectFeed.setMinimumSize(QtCore.QSize(350, 40))
        self.selectFeed.setObjectName("selectFeed")
        self.selectFeed.addItem("")
        self.selectFeed.addItem("")
        self.selectFeed.addItem("")
        self.selectFeed.addItem("")
        self.selectFeed.addItem("")
        self.horizontalLayout_4.addWidget(self.selectFeed)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.infoAboutAnimal = QtWidgets.QLabel(self.centralwidget)
        self.infoAboutAnimal.setMinimumSize(QtCore.QSize(500, 50))
        self.infoAboutAnimal.setStyleSheet("color: #B15B2E;")
        self.infoAboutAnimal.setAlignment(QtCore.Qt.AlignCenter)
        self.infoAboutAnimal.setObjectName("infoAboutAnimal")
        self.horizontalLayout_5.addWidget(self.infoAboutAnimal)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.btn_confirm_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_confirm_5.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_confirm_5.setStyleSheet("QPushButton{\n"
"    background-color: #313335;\n"
"    border: 3px qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C622FF, stop:1 #1D6BFF);\n"
"    border-style: solid;\n"
"    border-radius: 12%;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:after{\n"
"background-color:  #5C6164;\n"
"}\n"
"")
        self.btn_confirm_5.setObjectName("btn_confirm_5")
        self.horizontalLayout_6.addWidget(self.btn_confirm_5)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem18)
        ChangeFeedWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeFeedWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        ChangeFeedWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeFeedWindow)
        self.statusbar.setObjectName("statusbar")
        ChangeFeedWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeFeedWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangeFeedWindow)

    def retranslateUi(self, ChangeFeedWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangeFeedWindow.setWindowTitle(_translate("ChangeFeedWindow", "MainWindow"))
        self.label.setText(_translate("ChangeFeedWindow", "Заявка"))
        self.label_3.setText(_translate("ChangeFeedWindow", "Сотрудник"))
        self.label_2.setText(_translate("ChangeFeedWindow", "Тип корма"))
        self.selectFeed.setItemText(0, _translate("ChangeFeedWindow", "Овёс"))
        self.selectFeed.setItemText(1, _translate("ChangeFeedWindow", "Пшеница"))
        self.selectFeed.setItemText(2, _translate("ChangeFeedWindow", "Морковка"))
        self.selectFeed.setItemText(3, _translate("ChangeFeedWindow", "Биокорм"))
        self.selectFeed.setItemText(4, _translate("ChangeFeedWindow", "Комбикорм"))
        self.infoAboutAnimal.setText(_translate("ChangeFeedWindow", "Инфа о животном"))
        self.btn_confirm_5.setText(_translate("ChangeFeedWindow", "Подтвердить"))
        self.btn_confirm_5.setShortcut(_translate("ChangeFeedWindow", "Return"))
