# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inspection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InspectionWindow(object):
    def setupUi(self, InspectionWindow):
        InspectionWindow.setObjectName("InspectionWindow")
        InspectionWindow.resize(823, 676)
        self.centralwidget = QtWidgets.QWidget(InspectionWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #242424;\n"
"    font-family: Roboto;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: 100px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.animal_box = QtWidgets.QComboBox(self.centralwidget)
        self.animal_box.setMinimumSize(QtCore.QSize(400, 40))
        self.animal_box.setObjectName("animal_box")
        self.horizontalLayout.addWidget(self.animal_box)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.employee_box = QtWidgets.QComboBox(self.centralwidget)
        self.employee_box.setMinimumSize(QtCore.QSize(350, 40))
        self.employee_box.setObjectName("employee_box")
        self.horizontalLayout_2.addWidget(self.employee_box)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.status_box = QtWidgets.QComboBox(self.centralwidget)
        self.status_box.setMinimumSize(QtCore.QSize(350, 40))
        self.status_box.setObjectName("status_box")
        self.status_box.addItem("")
        self.status_box.addItem("")
        self.horizontalLayout_4.addWidget(self.status_box)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.info_animal = QtWidgets.QLabel(self.centralwidget)
        self.info_animal.setMinimumSize(QtCore.QSize(500, 50))
        self.info_animal.setStyleSheet("color: #B15B2E;")
        self.info_animal.setText("")
        self.info_animal.setAlignment(QtCore.Qt.AlignCenter)
        self.info_animal.setObjectName("info_animal")
        self.horizontalLayout_5.addWidget(self.info_animal)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.img_animal_1 = QtWidgets.QLabel(self.centralwidget)
        self.img_animal_1.setMinimumSize(QtCore.QSize(200, 200))
        self.img_animal_1.setMaximumSize(QtCore.QSize(200, 200))
        self.img_animal_1.setText("")
        self.img_animal_1.setScaledContents(True)
        self.img_animal_1.setObjectName("img_animal_1")
        self.horizontalLayout_3.addWidget(self.img_animal_1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.img_feed_1 = QtWidgets.QLabel(self.centralwidget)
        self.img_feed_1.setMinimumSize(QtCore.QSize(200, 200))
        self.img_feed_1.setMaximumSize(QtCore.QSize(200, 200))
        self.img_feed_1.setText("")
        self.img_feed_1.setScaledContents(True)
        self.img_feed_1.setObjectName("img_feed_1")
        self.horizontalLayout_3.addWidget(self.img_feed_1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.img_gender_1 = QtWidgets.QLabel(self.centralwidget)
        self.img_gender_1.setMinimumSize(QtCore.QSize(200, 200))
        self.img_gender_1.setMaximumSize(QtCore.QSize(200, 200))
        self.img_gender_1.setText("")
        self.img_gender_1.setScaledContents(True)
        self.img_gender_1.setObjectName("img_gender_1")
        self.horizontalLayout_3.addWidget(self.img_gender_1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem20)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: #313335;\n"
"    border: 3px qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C622FF, stop:1 #1D6BFF);\n"
"    border-style: solid;\n"
"    border-radius: 12%;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:after{\n"
"background-color:  #5C6164;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem23)
        InspectionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InspectionWindow)
        QtCore.QMetaObject.connectSlotsByName(InspectionWindow)

    def retranslateUi(self, InspectionWindow):
        _translate = QtCore.QCoreApplication.translate
        InspectionWindow.setWindowTitle(_translate("InspectionWindow", "MainWindow"))
        self.label.setText(_translate("InspectionWindow", "Номер животного"))
        self.label_3.setText(_translate("InspectionWindow", "Сотрудник"))
        self.label_2.setText(_translate("InspectionWindow", "Статус"))
        self.status_box.setItemText(0, _translate("InspectionWindow", "Больное"))
        self.status_box.setItemText(1, _translate("InspectionWindow", "Здоровое"))
        self.pushButton.setText(_translate("InspectionWindow", "Подтвердить"))
        self.pushButton.setShortcut(_translate("InspectionWindow", "Return"))
