# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weight.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeightForm(object):
    def setupUi(self, WeightForm):
        WeightForm.setObjectName("WeightForm")
        WeightForm.resize(734, 565)
        self.centralwidget = QtWidgets.QWidget(WeightForm)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #242424;\n"
"    font-family: Roboto;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: 100px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.numberAnimal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.numberAnimal.setMinimumSize(QtCore.QSize(250, 40))
        self.numberAnimal.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"    background-color:  #313335;\n"
"}")
        self.numberAnimal.setDecimals(0)
        self.numberAnimal.setMinimum(1.0)
        self.numberAnimal.setMaximum(10000.0)
        self.numberAnimal.setObjectName("numberAnimal")
        self.horizontalLayout_5.addWidget(self.numberAnimal)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.Weight = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Weight.setMinimumSize(QtCore.QSize(250, 40))
        self.Weight.setSizeIncrement(QtCore.QSize(0, 0))
        self.Weight.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"    background-color:  #313335;\n"
"}")
        self.Weight.setDecimals(0)
        self.Weight.setMaximum(100000.0)
        self.Weight.setObjectName("Weight")
        self.horizontalLayout_4.addWidget(self.Weight)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.InfoAnimal = QtWidgets.QLabel(self.centralwidget)
        self.InfoAnimal.setStyleSheet("color: #B15B2E")
        self.InfoAnimal.setObjectName("InfoAnimal")
        self.horizontalLayout_3.addWidget(self.InfoAnimal)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.img_animal = QtWidgets.QLabel(self.centralwidget)
        self.img_animal.setMinimumSize(QtCore.QSize(200, 200))
        self.img_animal.setMaximumSize(QtCore.QSize(150, 150))
        self.img_animal.setText("")
        self.img_animal.setScaledContents(True)
        self.img_animal.setObjectName("img_animal")
        self.horizontalLayout.addWidget(self.img_animal)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.img_feed = QtWidgets.QLabel(self.centralwidget)
        self.img_feed.setMinimumSize(QtCore.QSize(200, 200))
        self.img_feed.setMaximumSize(QtCore.QSize(200, 200))
        self.img_feed.setText("")
        self.img_feed.setScaledContents(True)
        self.img_feed.setObjectName("img_feed")
        self.horizontalLayout.addWidget(self.img_feed)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.img_gender = QtWidgets.QLabel(self.centralwidget)
        self.img_gender.setMinimumSize(QtCore.QSize(200, 200))
        self.img_gender.setMaximumSize(QtCore.QSize(200, 200))
        self.img_gender.setText("")
        self.img_gender.setScaledContents(True)
        self.img_gender.setObjectName("img_gender")
        self.horizontalLayout.addWidget(self.img_gender)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.btn_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_confirm.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_confirm.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_confirm.setStyleSheet("QPushButton{\n"
"    background-color: #313335;\n"
"    border: 3px qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #C622FF, stop:1 #1D6BFF);\n"
"    border-style: solid;\n"
"    border-radius: 12%;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QPushButton:after{\n"
"background-color:  #5C6164;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:  #313335;\n"
"}")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_2.addWidget(self.btn_confirm)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem19)
        WeightForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(WeightForm)
        QtCore.QMetaObject.connectSlotsByName(WeightForm)

    def retranslateUi(self, WeightForm):
        _translate = QtCore.QCoreApplication.translate
        WeightForm.setWindowTitle(_translate("WeightForm", "MainWindow"))
        self.label.setText(_translate("WeightForm", "Номер животного"))
        self.label_3.setText(_translate("WeightForm", "Текущий вес"))
        self.InfoAnimal.setText(_translate("WeightForm", "Инфа о животном"))
        self.btn_confirm.setText(_translate("WeightForm", "Подтвердить"))
